#define inti_dt 1
#define booli_dt 2
#define stringi_dt 3
#define oare 4
#define altfel 5
#define inject 6
#define eject 7
#define ejectS 8
#define arrayi 9
#define whale 10
#define ford 11
#define si 12
#define sau 13
#define id 14
#define ct 15
#define plus 16
#define MINUS 17
#define MULTIPLY 18
#define DIVISION 19
#define REMAINDER 20
#define LESS 21
#define LESS_OR_EQUAL 22
#define EQUAL 23
#define GREATER_OR_EQUAL 24
#define GREATER 25
#define ASSIGN 26
#define OPEN_ACCOL 27
#define CLOSED_ACCOL 28
#define OPEN_SQUARE 29
#define CLOSED_SQUARE 30
#define OPEN_ROUND 31
#define CLOSED_ROUND 32
#define SEMI_COL 33
#define COMMA 34